# Generated by Django 2.2.7 on 2019-11-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='number',
            new_name='number_table',
        ),
    ]
