# Generated by Django 2.2.7 on 2019-11-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20191115_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='num_table',
            new_name='number_table',
        ),
    ]
